version: '3'

services:
  # PHP Laravel Application
  app:
    build:
      context: ./webshop-backend
      dockerfile: Dockerfile
    container_name: webshop-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./webshop-backend:/var/www
    networks:
      - webshop-network
    depends_on:
      - mysql

  # Nginx Service for Laravel
  nginx:
    image: nginx:alpine
    container_name: webshop-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./webshop-backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - webshop-network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: webshop-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lse_webshop
      MYSQL_USER: webshop_user
      MYSQL_PASSWORD: webshop_password
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webshop-network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webshop-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - webshop-network
    depends_on:
      - mysql

networks:
  webshop-network:
    driver: bridge

volumes:
  dbdata:
    driver: local